### ISSUE TITLE
Range needed for IPAM

### ISSUE THREAD

**Issue by midokura-agustin** [yamt/midonet-kubernetes#1]
https://github.com/yamt/midonet-kubernetes/blob/0c87e38ab3e994c4ba35be439697612d341be0e4/cmd/midonet-kube-node/cniconfig.go#L29

There should be a range defined for IPAM, otherwise first IP address assigned to first pod (normally kube-dns) is the one ending in .2, the same as assigned to the node itself.

IPAM parameters are, for example:
       "rangeStart": "10.77.0.20",
       "rangeEnd": "10.77.0.50",

**Comment by yamt** [comment]
the address of the node is excluded programmatically.
https://github.com/yamt/midonet-kubernetes/blob/1.0/pkg/cni/k8s/k8s.go#L118-L123
do you mean it isn't working?

**Comment by midokura-agustin** [comment]
Yes it isn't. DNS is assigned IP address ending in ".2" which is the same assigned to the node. As a workarround we don't clean local ipam-database and later installations/tests consider all those addresses as already  assigned
```
root@master:/var/lib/cni/networks/midonet-pod-network# ls
10.1.0.9  last_reserved_ip.0
```
